CREATE TABLE IF NOT EXISTS students (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    department VARCHAR(100),
    semester INT,
    gpa DOUBLE,
    attendance_pct DOUBLE,
    subject_attendance_avg DOUBLE,
    lms_activity_hrs INT,
    placement_mock_score INT,
    internal_assessment_avg DOUBLE,
    backlogs INT,
    subject_performance_avg DOUBLE,
    lms_login_frequency INT,
    assignment_completion_pct DOUBLE,
    events_participated INT,
    clubs_participated INT,
    hackathons_participated INT,
    certifications INT,
    aptitude_score DOUBLE,
    coding_score DOUBLE,
    mock_interview_score DOUBLE,
    technical_skill_score DOUBLE,
    soft_skill_score DOUBLE,
    student_satisfaction_score DOUBLE,
    faculty_feedback_score DOUBLE,
    success_score DOUBLE,
    risk_category VARCHAR(30),
    academic_risk VARCHAR(30),
    placement_risk VARCHAR(30),
    academic_score DOUBLE,
    attendance_score DOUBLE,
    lms_score DOUBLE,
    engagement_score DOUBLE,
    placement_readiness_score DOUBLE,
    skills_score DOUBLE,
    feedback_score DOUBLE,
    data_coverage_pct DOUBLE,
    actionable_insight VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS intervention_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL,
    faculty_name VARCHAR(100),
    action_taken TEXT,
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
